services:
  nextapp:
    container_name: nextapp
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./:/app
      - /app/node_modules  
    networks:
      - my_network

    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

networks:
  my_network:
    driver: bridge