services:
  nextapp:
    container_name: nextapp
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - "3002:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
